### PR TITLE
Add Action Route for Resume for Purchase

### PR DESCRIPTION
**Pull request by lemadmax**

### CODE REVIEW

**Comment by TimothyXu** [comment]
Thank you for doing this! There are gonna be conflicts between you and Jingwei's story since he's currently refactoring the code to Flask-RESTX. I don't know how we should do this, perhaps wait till he's done then reformat this PR? Since this story comes after the refactoring (we did it hoping that we wouldn't have to do double work life this, hoping that the refactoring would be finished first then can just do this easily)

**Comment by Adora2401** [comment]
I have resolved the existing conflicts but not sure if my changes exactly match Zhengrui's mind, maybe someone will help check this part.

**Comment by TimothyXu** [comment]
1. Need to refactor into Flask-X/swagger (including creating a new swagger data model now that we have this extra hold column, and add swagger docs to the route)
2. Per Professor's comments need to change the route to shopcarts/<int:user_id>/items/<int:item_id>/resume

**Comment by lemadmax** [comment]
Alright, I will cancel this pull request and fix everything. Maybe we should merge all pull requests before we start developing.

**Comment by kdokm** [comment]
> Alright, I will cancel this pull request and fix everything. Maybe we should merge all pull requests before we start developing.

Ok, you can work on the latest version. I believe most of the things you added are kept.

**Comment by TimothyXu** [comment]
Yes block settings on ZenHub will help. Also thank you for pointing out my mistake @kdokm and please ignore what I said about 3. missing behave BDD tests

**Review by yjjw — APPROVED** [review]

**Pull request merged**
