### PR TITLE
UI for get_shopcarts

### PR DESCRIPTION
**Pull request by TimothyXu**

### CODE REVIEW

**Review by yjjw — COMMENTED** [review]
Just a minor thing, in line 75 of the feature file, there is an extra space in "ring1".
Also, when we enter "1003" as the user id, if there is a better wording to describe that we get nothing in the results?  I am not experienced on this part, just curious

**Comment by kdokm** [comment]
> Just a minor thing, in line 75 of the feature file, there is an extra space in "ring1". Also, when we enter "1003" as the user id, if there is a better wording to describe that we get nothing in the results? I am not experienced on this part, just curious

That extra space is my typo in story, sorry for that. I fixed the text in the story just now. We may try to see if some fields are empty, but I just think it is enough for the given data.

**Comment by yjjw** [comment]
> > Just a minor thing, in line 75 of the feature file, there is an extra space in "ring1". Also, when we enter "1003" as the user id, if there is a better wording to describe that we get nothing in the results? I am not experienced on this part, just curious
> 
> That extra space is my typo in story, sorry for that. I fixed the text in the story just now. We might be able to see if some fields are empty, although maybe it is a little different to check fileds in table. I just think it is enough for the given data, if you want, I can try to figure out this.

That is fine, in the given scenario, I think the current testing should be good to go

**Comment by TimothyXu** [comment]
Fixed and ready for merge.

**Pull request merged**
