### PR TITLE
initial working version of UI-Create-Item

### PR DESCRIPTION
**Pull request by Adora2401**

### CODE REVIEW

**Comment by TimothyXu** [comment]
I think everything looks fine after changing parseInt to parseFloat when getting the price in the js file, just need to sort out the BDD tests then this is done

**Comment by TimothyXu** [comment]
I'm fixing the tests for you don't need to do anything hang on

**Comment by Adora2401** [comment]
> I'm fixing the tests for you, you don't need to do anything hang on

Thank you. I am not sure why the TimesoutException happens as all the messages in BDD test are matched.

**Comment by TimothyXu** [comment]
> > I'm fixing the tests for you, you don't need to do anything hang on
> 
> Thank you. I am not sure why the TimesoutException happens as all the messages in BDD test are matched.

I believe just typos. Waiting for the GitHub CI to pass before approving this PR

**Pull request merged**
