### PR TITLE
first working version of read an item in a certain shopcart

### PR DESCRIPTION
**Pull request by Adora2401**
Add read_an_item(shopcart_id, item_id) in routes.py
Add test_read_an_item(self) and test_read_an_item_not_found(self) in test_routes.py

### CODE REVIEW

**Comment by Adora2401** [comment]
Sorry for the first version. I found some of annotation not clear. I will quick check and commit again.

**Comment by Adora2401** [comment]
Second version pushed.

**Comment by Adora2401** [comment]
Third version solved the conflicts.

**Review by kdokm — APPROVED** [review]

**Comment by yjjw** [comment]
Sorry, but shouldn't we get status code 404 when the requested shopcart id or the requested item id does not exist?
Seems that the current version does not return 404

**Comment by yjjw** [comment]
Oh never mind, saw the test not found out there.

**Pull request merged**
