### PR TITLE
Codecov in tdd.yml

### PR DESCRIPTION
**Pull request by yjjw**
Added upload action for codecov

### CODE REVIEW

**Comment by kdokm** [comment]
Codecov still shows error. Did we set up codecov well before?

**Comment by yjjw** [comment]
Actually we do not set up codecov successfully before. 
I don't  what else we should add besides the .yml file after checking the zoom video and the lecture slides.
Actually I do not see codecov set up correctly even when I did the lab.
Do I miss something here?

**Comment by TimothyXu** [comment]
It looks like Codecov is working now right? In the current PR there is a Codecov bot comment

**Comment by yjjw** [comment]
> It looks like Codecov is working now right? In the current PR there is a Codecov bot comment

Yuh, looks like working now. I guess it only works after the change is pushed to main

**Pull request merged**
