### PR TITLE
adding hold related code in service and test

### PR DESCRIPTION
**Pull request by Adora2401**
Added code about route for 'hold for later', waiting for the previous conflict resolved.

### CODE REVIEW

**Comment by TimothyXu** [comment]
1. Need to refactor into Flask-X/swagger (including creating a new swagger data model now that we have this extra hold column, and add swagger docs to the route)
2. Per Professor's comments need to change the route to shopcarts/<int:user_id>/items/<int:item_id>/resume
3. Missing behave BDD tests (criteria already in ZenHub)

**Comment by Adora2401** [comment]
> 1. Need to refactor into Flask-X/swagger (including creating a new swagger data model now that we have this extra hold column, and add swagger docs to the route)
> 2. Per Professor's comments need to change the route to shopcarts/int:user_id/items/int:item_id/resume
> 3. Missing behave BDD tests (criteria already in ZenHub)
Thanks Timothy, 1&2 have been done. I still have no idea about 3.

**Comment by Adora2401** [comment]
Hi, I have a question about the BDD test for our new feature "Hold for later". As it's a feature for user instead of Shopcart Store Owner in our original shopcarts.feature, until now I just updated shopcarts.feature, shopcarts_steps.py, rest_api.js, index.html to add "hold" in column and table so that the Shopcart Store Owner could view the True/False in the demo page. Additionally, I didn't add any scenrio in shopcarts.feature as I am not sure whether we need it or not. Also, these changes lead BDD test failed.  Could anyone take this part or give me some advice? I have no idea why resp doesn't get the data. Thank you all so much for your time and help.

**Comment by kdokm** [comment]
> Hi, I have a question about the BDD test for our new feature "Hold for later". As it's a feature for user instead of Shopcart Store Owner in our original shopcarts.feature, until now I just updated shopcarts.feature, shopcarts_steps.py, rest_api.js, index.html to add "hold" in column and table so that the Shopcart Store Owner could view the True/False in the demo page. Additionally, I didn't add any scenrio in shopcarts.feature as I am not sure whether we need it or not. Also, these changes lead BDD test failed. Could anyone take this part or give me some advice? I have no idea why resp doesn't get the data. Thank you all so much for your time and help.

I think maybe it is because the “hold” data passed in shopcart_steps.py is not boolean, which causes create fails. However, I haven’t check it so I’m not sure. I guess you can observe logs in ‘honcho start’ terminal when running behave to see what happens. When I have time, if this problem is still not solved, I can take care of it.

**Comment by Adora2401** [comment]
> > Hi, I have a question about the BDD test for our new feature "Hold for later". As it's a feature for user instead of Shopcart Store Owner in our original shopcarts.feature, until now I just updated shopcarts.feature, shopcarts_steps.py, rest_api.js, index.html to add "hold" in column and table so that the Shopcart Store Owner could view the True/False in the demo page. Additionally, I didn't add any scenrio in shopcarts.feature as I am not sure whether we need it or not. Also, these changes lead BDD test failed. Could anyone take this part or give me some advice? I have no idea why resp doesn't get the data. Thank you all so much for your time and help.
> 
> I think maybe it is because the “hold” data passed in shopcart_steps.py is not boolean, which causes the initial create fails. However, I haven’t check it so I’m not sure. I guess you can observe logs in ‘honcho start’ terminal when running behave to see what happens. When I have time, if this problem is still not solved, I can take care of it.

Thanks Yuwen, solved.

**Comment by kdokm** [comment]
> 1. Need to refactor into Flask-X/swagger (including creating a new swagger data model now that we have this extra hold column, and add swagger docs to the route)
> 2. Per Professor's comments need to change the route to shopcarts/int:user_id/items/int:item_id/resume
> 3. Missing behave BDD tests (criteria already in ZenHub)

I think BDD tests are for the UI, so this version is enough for the connected story now.

**Comment by TimothyXu** [comment]
> > 1. Need to refactor into Flask-X/swagger (including creating a new swagger data model now that we have this extra hold column, and add swagger docs to the route)
> 
> > 2. Per Professor's comments need to change the route to shopcarts/int:user_id/items/int:item_id/resume
> 
> > 3. Missing behave BDD tests (criteria already in ZenHub)
> 
> 
> 
> I think BDD tests are for the UI, so this version is enough for the connected story now.

Oh you're absolutely right! We should move the BDD acceptance criteria for this story into the acceptance criteria for the 'UI for hold' story, and similarly with 'UI for resume'. Thank you for catching this

**Pull request merged**
